spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_routing_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Change to 'update' after first run
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  application:
    name: payment-routing-engine

server:
  port: 8080

logging:
  level:
    com.fawry.paymentroutingengine: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE